name: "sensor-pack"
author: "ViperZ28"
description: "Sensor pack"
category: ["FPV", "Sensor"]
sensor: ""  # Set sensor file if needed
status: "Community"
tags: ["jumbo-packets"]
files: {}

    

    
